name: Update AdBlock Rules

# Запускать скрипт: каждую пятницу в полночь + можно запустить вручную
on:
  schedule:
    - cron: '0 0 * * 5' 
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Download EasyList rules
        run: curl -o easylist.txt "https://easylist.to/easylist/easylist.txt"

      - name: Convert to Safari JSON
        run: node convert.js

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update Safari blocker rules"
          file_pattern: "blockerList.json"
